services:
  # Frontend deployment (Vercel)
  - type: web
    name: odiadev-frontend
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_SUPABASE_URL
        value: https://nyrvnskbkitrazudrkkc.supabase.co
      - key: VITE_SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im55cnZuc2tia2l0cmF6dWRya2tjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NjAwNTQsImV4cCI6MjA3MjMzNjA1NH0.4OjZqbrvXrF3N0CNpzUndh9HTKCtXiadA6NRQv98fCg
      - key: VITE_AGENT_API_URL
        value: https://odiadev-brain.onrender.com
      - key: VITE_TTS_PROXY_URL
        value: https://nyrvnskbkitrazudrkkc.supabase.co/functions/v1/tts
      - key: VITE_SITE_URL
        value: https://odiadev.vercel.app

  # Backend AI Brain deployment
  - type: web
    name: odiadev-brain
    env: node
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GROQ_API_KEY
        fromService:
          type: secret
          name: groq-api-key
      - key: ALLOWED_ORIGINS
        value: https://odiadev.vercel.app,https://odia.dev,http://localhost:5173
      - key: RENDER_EXTERNAL_URL
        value: https://odiadev-brain.onrender.com