services:
  - type: web
    name: odiadev-brain
    env: node
    rootDir: .
    buildCommand: npm install --legacy-peer-deps
    startCommand: node server/brain.js
    healthCheckPath: /healthz
    plan: starter
    region: oregon
    envVars:
      - key: NODE_ENV
        value: production

  - type: static
    name: odiadev-frontend
    rootDir: .
    buildCommand: npm install --legacy-peer-deps && npm run build
    publishPath: dist
    plan: starter
    region: oregon
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_SITE_URL
        value: https://odia.dev
      - key: VITE_AGENT_API_URL
        value: https://odiadev-brain.onrender.com/api/chat
